# Generated by Django 4.2.4 on 2023-09-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_investment_invesments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invesments',
            name='returns',
            field=models.IntegerField(default=0),
        ),
    ]
