# Generated by Django 4.2.5 on 2023-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_deposits_amount_alter_earnings_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='charge_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposits',
            name='currency',
            field=models.CharField(default='USDT', max_length=10),
            preserve_default=False,
        ),
    ]
