# Generated by Django 4.2.5 on 2023-09-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_deposits_charge_id_deposits_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ewallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
