# Generated by Django 4.2.5 on 2023-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_investments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
