# Generated by Django 4.2.5 on 2023-09-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_investments_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
