# Generated by Django 4.2.5 on 2023-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_deposits_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='percentage_returned',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
