# Generated by Django 4.2.5 on 2023-10-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_investments_percentage_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='status',
            field=models.CharField(default='created', max_length=100),
        ),
    ]
