# Generated by Django 4.2.5 on 2023-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_profile_country_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='aprroved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
    ]
