# Generated by Django 4.2.5 on 2023-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_frequentlyaskedquestions_withdrawals_aprroved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
