# Generated by Django 4.2.5 on 2023-10-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_frequentlyaskedquestions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_authorization', models.BooleanField(default=False)),
            ],
        ),
    ]
